/**
 * Routines App — the standalone page for routines (scheduled prompts that
 * run in the background and post results to the Home feed).
 *
 * Since 2026-07-31 this page is routines-ONLY: non-scheduled prompt notes
 * ("saved prompts") live in the Notes app like any other note, with the
 * editor's prompt config panel. Scheduling a saved prompt there turns it
 * into a routine and moves it here; the app id stays 'prompts' so deep
 * links and tools keep working. The BACKEND IS UNCHANGED: a routine is
 * still a note in the shared `notes` blob, read and written through
 * NotePrompts — so sync, the assistant's scheduled-prompt tools, and the
 * PromptFeed scheduler keep working untouched. This file is UI only.
 *
 * Three in-page views:
 *  - list:   every routine
 *  - detail: one routine — body, config chips, actions, recent feed posts
 *  - form:   create/edit (always a routine; reuses the old modal's
 *            .prompt-mgr-* classes so the styling carries)
 *
 * Entry points: the launcher tile, Home feed's "Manage routines" button,
 * the feed post overlay's routine link (all via
 * AppManager.openApp('prompts') / PromptsApp.open()).
 */

const PromptsApp = {
    _view: 'list',      // 'list' | 'detail' | 'form'
    _openId: null,      // detail target; form target (null = create)
    _bound: false,
    // List-table state. Sort persists per-machine (localStorage, same as
    // Portfolio's tables); search and the schedule filter reset per visit.
    _table: { q: '', interval: 'all', sort: null },

    init() {
        if (this._bound) return;
        this._bound = true;
        document.getElementById('prompts-add-btn')?.addEventListener('click', () => {
            this._view = 'form';
            this._openId = null;
            this.render();
        });
    },

    /** External entry: open the page on the list, a detail, or the create form. */
    open(opts = {}) {
        if (opts.create) { this._view = 'form'; this._openId = null; }
        else if (opts.id) { this._view = 'detail'; this._openId = opts.id; }
        else { this._view = 'list'; this._openId = null; }
        AppManager.openApp('prompts');
        this.render();
    },

    // --- Data (all reads go through the notes blob — storage source of truth) ---

    _prompts() {
        const list = NotePrompts.list();
        return list.sort((a, b) =>
            new Date(b.modifiedAt || 0).getTime() - new Date(a.modifiedAt || 0).getTime());
    },

    _note(id) {
        return NotePrompts.list().find(n => n.id === id) || null;
    },

    /** Feed posts generated by this prompt, newest first. */
    _outputs(promptId) {
        const d = StorageManager.get('notes');
        const notes = (d && Array.isArray(d.notes)) ? d.notes : [];
        return notes
            .filter(n => NoteTemplates.resolve(n) === 'feed' && n.feed && n.feed.promptId === promptId)
            .sort((a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0));
    },

    _lastRunLabel(p) {
        const last = (typeof PromptFeed !== 'undefined' && PromptFeed.data) ? PromptFeed.data.runs[p.id] : null;
        return last ? `ran ${PromptFeed._timeAgo(last)}` : 'not run yet';
    },

    _chips(cfg) {
        return [
            cfg.offline
                ? `<span class="prompt-mgr-chip">${UIUtils.escapeHtml(NotePrompts.scheduleLabel(cfg))}</span>`
                : `<span class="prompt-mgr-chip">${cfg.target === 'browser' ? 'runs in Browser' : 'runs in Assistant'}</span>`,
            cfg.web ? '<span class="prompt-mgr-chip">&#127760; web</span>' : '',
            cfg.useContext ? '<span class="prompt-mgr-chip">&#10024; my context</span>' : ''
        ].filter(Boolean).join('');
    },

    // --- Render ---

    // Deep-link to one prompt's detail page — used by the assistant's record
    // pills ("Prompt · Market Close Review" under an answer) and any other
    // cross-app link. Safe before init: render() falls back to the list if
    // the id is unknown.
    openPrompt(id) {
        this._view = 'detail';
        this._openId = id;
        this.render();
    },

    render() {
        const container = document.getElementById('prompts-main');
        if (!container) return;
        // The open prompt may have been deleted (or synced away).
        if (this._openId && !this._note(this._openId)) {
            this._view = 'list';
            this._openId = null;
        }
        this._renderCrumbs();
        if (this._view === 'form') this._renderForm(container, this._openId ? this._note(this._openId) : null);
        else if (this._view === 'detail') this._renderDetail(container, this._note(this._openId));
        else this._renderList(container);
    },

    /**
     * The page title, through Breadcrumb like every other app page. It used
     * to be a bare text node in index.html, which meant it missed the
     * `.breadcrumb-current` styling every other title gets (600 weight, and
     * the padding that puts the first glyph on the shared left edge) — so
     * this one page's heading sat lighter and 8px to the left of Actions,
     * Notes and the rest. The trail also names where you are inside the app,
     * which is what the detail and form states were missing.
     */
    _renderCrumbs() {
        if (typeof Breadcrumb === 'undefined') return;
        const toList = () => { this._view = 'list'; this._openId = null; this.render(); };
        const note = this._openId ? this._note(this._openId) : null;
        if (this._view === 'detail' && note) {
            Breadcrumb.render('prompts-breadcrumb', [
                { label: 'Routines', action: toList },
                { label: note.title || 'Untitled routine' }
            ]);
        } else if (this._view === 'form') {
            Breadcrumb.render('prompts-breadcrumb', [
                { label: 'Routines', action: toList },
                { label: note ? 'Edit routine' : 'New routine' }
            ]);
        } else {
            Breadcrumb.render('prompts-breadcrumb', [{ label: 'Routines' }]);
        }
    },

    // Table sort: which columns open ascending on first click.
    _TEXT_COLS: ['title', 'schedule'],

    _tableSort() {
        if (!this._table.sort) {
            let stored = null;
            try { stored = JSON.parse(localStorage.getItem('routines-sort') || 'null'); } catch (e) { /* default stands */ }
            this._table.sort = (stored && stored.col) ? stored : { col: 'schedule', dir: 'asc' };
        }
        return this._table.sort;
    },

    _setTableSort(col) {
        const s = this._tableSort();
        if (s.col === col) s.dir = s.dir === 'asc' ? 'desc' : 'asc';
        else { s.col = col; s.dir = this._TEXT_COLS.includes(col) ? 'asc' : 'desc'; }
        try { localStorage.setItem('routines-sort', JSON.stringify(s)); } catch (e) { /* ignore */ }
        this.render();
    },

    _renderList(container) {
        // Routines only — saved (non-scheduled) prompt notes live in Notes.
        const all = this._prompts().filter(p => NotePrompts.config(p).offline);
        const esc = UIUtils.escapeHtml;

        if (!all.length) {
            container.innerHTML = `
                <div class="prompt-mgr-list prompts-page-list">
                    <div class="prompt-mgr-empty">
                        <span class="prompt-mgr-empty-icon" aria-hidden="true">&#9201;</span>
                        <p class="prompt-mgr-empty-text">No routines yet. A routine runs a prompt on a schedule<br>and posts each result to your Home feed.</p>
                        <button class="primary-btn prompt-mgr-empty-add" type="button">Create your first routine</button>
                    </div>
                </div>`;
            container.querySelector('.prompt-mgr-empty-add')?.addEventListener('click', () => {
                this._view = 'form'; this._openId = null; this.render();
            });
            return;
        }

        const t = this._table;
        const sort = this._tableSort();
        const runs = (typeof PromptFeed !== 'undefined' && PromptFeed.data && PromptFeed.data.runs) || {};

        let rows = all.map(p => {
            const cfg = NotePrompts.config(p);
            return { p, cfg, body: NotePrompts.bodyText(p), last: runs[p.id] || null };
        });
        const q = t.q.trim().toLowerCase();
        if (q) rows = rows.filter(r =>
            (r.p.title || '').toLowerCase().includes(q) || r.body.toLowerCase().includes(q));
        if (t.interval !== 'all') rows = rows.filter(r => r.cfg.interval === t.interval);

        const ORDER = { hourly: 0, '6h': 1, daily: 2, weekdays: 3, weekly: 4 };
        const dir = sort.dir === 'asc' ? 1 : -1;
        const cmp = {
            title: (a, b) => (a.p.title || '').localeCompare(b.p.title || ''),
            schedule: (a, b) => (ORDER[a.cfg.interval] - ORDER[b.cfg.interval])
                || String(a.cfg.time || '99:99').localeCompare(String(b.cfg.time || '99:99')),
            web: (a, b) => (a.cfg.web ? 1 : 0) - (b.cfg.web ? 1 : 0),
            context: (a, b) => (a.cfg.useContext ? 1 : 0) - (b.cfg.useContext ? 1 : 0),
            lastRun: (a, b) => (Date.parse(a.last) || 0) - (Date.parse(b.last) || 0)
        }[sort.col] || (() => 0);
        rows.sort((a, b) => dir * cmp(a, b) || (a.p.title || '').localeCompare(b.p.title || ''));

        const th = (col, label, cls = '') => {
            const active = sort.col === col;
            const arrow = active ? (sort.dir === 'asc' ? '&#9650;' : '&#9660;') : '';
            return `<th class="routines-th ${cls}" data-col="${col}" role="button" tabindex="0"
                        aria-sort="${active ? (sort.dir === 'asc' ? 'ascending' : 'descending') : 'none'}"
                    >${label}${arrow ? `<span class="routines-sort-arrow">${arrow}</span>` : ''}</th>`;
        };
        const tr = (r) => `
            <tr class="routines-row" data-open-prompt="${esc(r.p.id)}" tabindex="0">
                <td class="routines-td-title">${esc(r.p.title || 'Untitled routine')}</td>
                <td class="routines-td-sched">${esc(NotePrompts.scheduleLabel(r.cfg))}</td>
                <td class="routines-td-flag">${r.cfg.web ? '&#10003;' : ''}</td>
                <td class="routines-td-flag">${r.cfg.useContext ? '&#10003;' : ''}</td>
                <td class="routines-td-ran">${r.last && typeof PromptFeed !== 'undefined' ? esc(PromptFeed._timeAgo(r.last)) : 'never'}</td>
                <td class="routines-td-actions">
                    <button class="prompt-mgr-iconbtn" data-run="${esc(r.p.id)}" type="button" title="Run now" aria-label="Run now">&#9654;</button>
                    <button class="prompt-mgr-iconbtn" data-edit="${esc(r.p.id)}" type="button" title="Edit" aria-label="Edit">&#9998;</button>
                    <button class="prompt-mgr-iconbtn prompt-mgr-del" data-del="${esc(r.p.id)}" type="button" title="Delete" aria-label="Delete">&#128465;</button>
                </td>
            </tr>`;

        const INTERVALS = [['all', 'All schedules'], ['hourly', 'Hourly'], ['6h', 'Every 6h'],
                           ['daily', 'Daily'], ['weekdays', 'Weekdays'], ['weekly', 'Weekly']];
        container.innerHTML = `
            <div class="routines-toolbar">
                <input id="routines-search" class="routines-search" type="search"
                       placeholder="Search routines" value="${esc(t.q)}" spellcheck="false">
                <select id="routines-filter" class="routines-filter" aria-label="Filter by schedule">
                    ${INTERVALS.map(([v, l]) => `<option value="${v}" ${t.interval === v ? 'selected' : ''}>${l}</option>`).join('')}
                </select>
                <span class="routines-count">${rows.length} of ${all.length}</span>
            </div>
            <table class="routines-table">
                <thead><tr>
                    ${th('title', 'Routine')}
                    ${th('schedule', 'Schedule')}
                    ${th('web', 'Web', 'routines-th-flag')}
                    ${th('context', 'Context', 'routines-th-flag')}
                    ${th('lastRun', 'Last run')}
                    <th class="routines-th-actions"></th>
                </tr></thead>
                <tbody>
                    ${rows.length ? rows.map(tr).join('')
                        : `<tr><td class="routines-table-empty" colspan="6">No routines match.</td></tr>`}
                </tbody>
            </table>`;

        // Search re-renders the table on each keystroke; the input is
        // rebuilt with it, so focus and caret are put back by hand.
        const search = container.querySelector('#routines-search');
        search.addEventListener('input', () => {
            this._table.q = search.value;
            const pos = search.selectionStart;
            this._renderList(container);
            const again = container.querySelector('#routines-search');
            again.focus();
            try { again.setSelectionRange(pos, pos); } catch (e) { /* type=search quirk */ }
        });
        container.querySelector('#routines-filter').addEventListener('change', (e) => {
            this._table.interval = e.target.value;
            this._renderList(container);
        });
        container.querySelectorAll('th[data-col]').forEach(h => {
            h.addEventListener('click', () => this._setTableSort(h.dataset.col));
            h.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); this._setTableSort(h.dataset.col); }
            });
        });
        container.querySelectorAll('[data-open-prompt]').forEach(row => {
            row.addEventListener('click', (e) => {
                if (e.target.closest('button')) return;
                this._view = 'detail'; this._openId = row.dataset.openPrompt; this.render();
            });
            row.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' && !e.target.closest('button')) {
                    this._view = 'detail'; this._openId = row.dataset.openPrompt; this.render();
                }
            });
        });
        container.querySelectorAll('[data-run]').forEach(b =>
            b.addEventListener('click', () => this._runNow(b.dataset.run, b)));
        container.querySelectorAll('[data-edit]').forEach(b =>
            b.addEventListener('click', () => {
                this._view = 'form'; this._openId = b.dataset.edit; this.render();
            }));
        container.querySelectorAll('[data-del]').forEach(b =>
            b.addEventListener('click', () => this._delete(b.dataset.del)));
    },

    _renderDetail(container, note) {
        if (!note) { this._view = 'list'; this._renderList(container); return; }
        const cfg = NotePrompts.config(note);
        const body = NotePrompts.bodyText(note);
        const outputs = this._outputs(note.id).slice(0, 20);
        const esc = UIUtils.escapeHtml;

        const postRows = outputs.map(o => {
            const when = o.createdAt
                ? new Date(o.createdAt).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
                : '';
            const tmp = document.createElement('div');
            tmp.innerHTML = o.content || '';
            const text = o.feed && o.feed.error
                ? o.feed.error
                : (tmp.textContent || '').replace(/\s+/g, ' ').trim();
            const preview = text.length > 160 ? text.slice(0, 160).trimEnd() + '…' : text;
            return `
                <button class="routines-post-row${o.feed && o.feed.error ? ' is-error' : ''}" data-open-post="${o.id}" type="button">
                    <span class="routines-post-when">${when}</span>
                    <span class="routines-post-preview">${esc(preview)}</span>
                </button>`;
        }).join('');

        // What the routine draws on, as one quiet value line.
        const uses = [cfg.web ? 'Web search' : '', cfg.useContext ? 'My context' : '']
            .filter(Boolean).join(' &middot; ');
        const scheduleValue = cfg.offline
            ? esc(NotePrompts.scheduleLabel(cfg))
            : (cfg.target === 'browser' ? 'runs in Browser' : 'runs in Assistant');
        const prop = (label, value) => `
            <div class="routines-prop">
                <span class="routines-prop-label">${label}</span>
                <span class="routines-prop-value">${value}</span>
            </div>`;

        container.innerHTML = `
            <div class="routines-detail-head">
                <h3 class="routines-detail-title">${esc(note.title || 'Untitled routine')}</h3>
                <div class="routines-detail-actions">
                    <button class="secondary-btn routines-act" data-run="${note.id}" type="button" title="Run this routine now">&#9654; Run now</button>
                    <button class="secondary-btn routines-act" data-edit="${note.id}" type="button">Edit</button>
                    <button class="secondary-btn routines-act routines-act-delete" data-del="${note.id}" type="button">Delete</button>
                </div>
            </div>
            <div class="routines-props">
                ${prop('Schedule', scheduleValue)}
                ${uses ? prop('Uses', uses) : ''}
                ${cfg.offline ? prop('Last run', esc(this._lastRunLabel(note))) : ''}
            </div>
            <div class="routines-prompt-section">
                <div class="detail-section-header">Prompt</div>
                <div class="routines-prompt-text">${esc(body) || '<span class="routines-empty">No prompt text yet — edit to add one.</span>'}</div>
            </div>
            ${outputs.length ? `
                <div class="routines-outputs">
                    <div class="detail-section-header">Feed posts</div>
                    ${postRows}
                </div>` : (cfg.offline ? '<p class="routines-empty">No runs yet — results will appear here and on your Home feed.</p>' : '')}
        `;

        container.querySelector('[data-run]')?.addEventListener('click', (e) => this._runNow(note.id, e.currentTarget));
        container.querySelector('[data-edit]')?.addEventListener('click', () => {
            this._view = 'form'; this.render();
        });
        container.querySelector('[data-del]')?.addEventListener('click', () => this._delete(note.id));
        container.querySelectorAll('[data-open-post]').forEach(b =>
            b.addEventListener('click', () => {
                if (typeof PromptFeed !== 'undefined' && PromptFeed.openPost) PromptFeed.openPost(b.dataset.openPost);
            }));
    },

    _renderForm(container, note) {
        const cfg = note ? NotePrompts.config(note) : { ...NotePrompts.DEFAULTS };
        const title = note ? (note.title || '') : '';
        const body = note ? NotePrompts.bodyText(note) : '';

        container.innerHTML = `
            <div class="routines-form">
                <input id="prompt-mgr-title" class="detail-title-input routines-title-input" type="text"
                       placeholder="Name this routine..." value="${UIUtils.escapeHtml(title)}" autocomplete="off" spellcheck="false">

                <div class="detail-section-header">Prompt</div>
                <textarea id="prompt-mgr-body" class="routines-body-input" rows="4"
                          placeholder="What should run on each schedule? Write it as a request to your assistant.">${UIUtils.escapeHtml(body)}</textarea>

                <div class="routines-props routines-form-props">
                    <input type="hidden" id="prompt-mgr-interval" value="${cfg.interval}">
                    <div class="routines-prop">
                        <span class="routines-prop-label">Run every</span>
                        <div class="prompt-mgr-seg" role="group" aria-label="Run every">
                            ${['hourly', '6h', 'daily', 'weekdays', 'weekly'].map(v => `
                                <button type="button" class="prompt-mgr-seg-btn ${cfg.interval === v ? 'active' : ''}" data-value="${v}" aria-pressed="${cfg.interval === v}">${NotePrompts.intervalLabel(v)}</button>`).join('')}
                        </div>
                    </div>
                    <div class="routines-prop prompt-mgr-time-row" ${['daily', 'weekdays', 'weekly'].includes(cfg.interval) ? '' : 'hidden'}>
                        <label class="routines-prop-label" for="prompt-mgr-time">At</label>
                        <input type="time" id="prompt-mgr-time" class="routines-time" value="${cfg.time || ''}">
                    </div>
                    <div class="routines-prop">
                        <span class="routines-prop-label">Uses</span>
                        <div class="routines-uses">
                            <label class="prompt-mgr-optchip" title="Let the model search the web during the run">
                                <input type="checkbox" id="prompt-mgr-web" ${cfg.web ? 'checked' : ''}>
                                <span>&#127760; Web search</span>
                            </label>
                            <label class="prompt-mgr-optchip" title="Run through the AI Assistant with your memory, goals, and schedule">
                                <input type="checkbox" id="prompt-mgr-context" ${cfg.useContext ? 'checked' : ''}>
                                <span>&#10024; My context</span>
                            </label>
                        </div>
                    </div>
                </div>
                <p class="routines-form-hint">Runs offline on your local model and posts each result to the Home feed.</p>

                <div class="routines-form-actions">
                    <button class="secondary-btn prompt-mgr-cancel" type="button">Cancel</button>
                    <button class="primary-btn prompt-mgr-save" type="button">${note ? 'Save changes' : 'Create routine'}</button>
                </div>
            </div>`;

        const back = () => {
            this._view = this._openId ? 'detail' : 'list';
            this.render();
        };
        container.querySelector('.prompt-mgr-cancel')?.addEventListener('click', back);

        // Segmented control writes into its hidden input so the save
        // handler reads plain fields (same recipe as the old modal form).
        container.querySelectorAll('.prompt-mgr-seg-btn').forEach(b =>
            b.addEventListener('click', () => {
                container.querySelector('#prompt-mgr-interval').value = b.dataset.value;
                container.querySelectorAll('.prompt-mgr-seg-btn').forEach(x => {
                    x.classList.toggle('active', x === b);
                    x.setAttribute('aria-pressed', String(x === b));
                });
                // A run time only makes sense for wall-clock intervals.
                container.querySelector('.prompt-mgr-time-row').hidden =
                    !['daily', 'weekdays', 'weekly'].includes(b.dataset.value);
            }));

        // Cmd/Ctrl+Enter from the prompt body saves — same muscle memory as
        // the assistant composer.
        container.querySelector('#prompt-mgr-body')?.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
                e.preventDefault();
                container.querySelector('.prompt-mgr-save')?.click();
            }
        });

        container.querySelector('.prompt-mgr-save')?.addEventListener('click', () => {
            const t = container.querySelector('#prompt-mgr-title').value.trim();
            const b = container.querySelector('#prompt-mgr-body').value.trim();
            if (!b) { UIUtils.showToast('Add a prompt first', 'error'); return; }
            const interval = container.querySelector('#prompt-mgr-interval').value;
            // Everything created or edited on this page is a routine; the
            // run target only matters for saved prompts (edited in Notes),
            // so an existing one is carried through untouched.
            const config = {
                target: cfg.target,
                offline: true,
                interval,
                time: ['daily', 'weekdays', 'weekly'].includes(interval)
                    ? (container.querySelector('#prompt-mgr-time').value || null) : null,
                web: container.querySelector('#prompt-mgr-web').checked,
                useContext: container.querySelector('#prompt-mgr-context').checked
            };
            const saved = note
                ? NotePrompts.update(note.id, { title: t, body: b, config })
                : NotePrompts.create({ title: t, body: b, config });
            // Nudge the scheduler so a newly created/enabled routine runs
            // soon instead of waiting for the next poll.
            if (typeof PromptFeed !== 'undefined' && PromptFeed.onPromptsChanged) {
                PromptFeed.onPromptsChanged();
            }
            UIUtils.showToast(note ? 'Routine updated' : 'Routine created', 'success');
            this._view = 'detail';
            this._openId = saved ? saved.id : this._openId;
            this.render();
        });

        setTimeout(() => container.querySelector('#prompt-mgr-title')?.focus(), 0);
    },

    // --- Actions ---

    async _runNow(id, btn) {
        const note = this._note(id);
        if (!note) return;
        const cfg = NotePrompts.config(note);
        if (cfg.offline) {
            if (typeof PromptFeed === 'undefined' || !PromptFeed.runNow) return;
            if (btn) btn.disabled = true;
            await PromptFeed.runNow(id);
            this.render();
        } else {
            NotePrompts.runDefault(note);
        }
    },

    async _delete(id) {
        const note = this._note(id);
        const noun = note && NotePrompts.config(note).offline ? 'routine' : 'prompt';
        const ok = await UIUtils.confirm(
            `Delete ${noun}`,
            `Delete &ldquo;${UIUtils.escapeHtml(note?.title || `this ${noun}`)}&rdquo;? This removes the ${noun} and stops its scheduled runs. Past feed posts stay.`,
            '🗑️',
            { confirmText: 'Delete' }
        );
        if (!ok) return;
        NotePrompts.remove(id);
        if (typeof PromptFeed !== 'undefined' && PromptFeed.render) PromptFeed.render();
        if (this._openId === id) { this._view = 'list'; this._openId = null; }
        this.render();
    }
};

AppManager.register('prompts', PromptsApp);
