/**
 * Routines App — the standalone page for routines (scheduled prompts that
 * run in the background and post results to the Home feed).
 *
 * Since 2026-07-31 this page is routines-ONLY: non-scheduled prompt notes
 * ("saved prompts") live in the Notes app like any other note, with the
 * editor's prompt config panel. Scheduling a saved prompt there turns it
 * into a routine and moves it here; the app id stays 'prompts' so deep
 * links and tools keep working. The BACKEND IS UNCHANGED: a routine is
 * still a note in the shared `notes` blob, read and written through
 * NotePrompts — so sync, the assistant's scheduled-prompt tools, and the
 * PromptFeed scheduler keep working untouched. This file is UI only.
 *
 * Three in-page views:
 *  - list:   every routine
 *  - detail: one routine — body, config chips, actions, recent feed posts
 *  - form:   create/edit (always a routine; reuses the old modal's
 *            .prompt-mgr-* classes so the styling carries)
 *
 * Entry points: the launcher tile, Home feed's "Manage routines" button,
 * the feed post overlay's routine link (all via
 * AppManager.openApp('prompts') / PromptsApp.open()).
 */

const PromptsApp = {
    _view: 'list',      // 'list' | 'detail' | 'form'
    _openId: null,      // detail target; form target (null = create)
    _bound: false,
    // List-table state. Sort persists per-machine (localStorage, same as
    // Portfolio's tables); search and the schedule filter reset per visit.
    _table: { q: '', interval: 'all', sort: null },

    init() {
        if (this._bound) return;
        this._bound = true;
        document.getElementById('prompts-add-btn')?.addEventListener('click', () => {
            this._view = 'form';
            this._openId = null;
            this.render();
        });
    },

    /** External entry: open the page on the list, a detail, or the create form. */
    open(opts = {}) {
        if (opts.create) { this._view = 'form'; this._openId = null; }
        else if (opts.id) { this._view = 'detail'; this._openId = opts.id; }
        else { this._view = 'list'; this._openId = null; }
        AppManager.openApp('prompts');
        this.render();
    },

    /**
     * The "Help me set up a routine" prompt pill — opens the assistant's
     * routine interview (start_routine_interview; the goals pattern). The
     * pill's wording contains "routine" on purpose: that word is what ships
     * the prompts tool group into the turn.
     */
    askNewRoutine() {
        if (typeof AgentUI === 'undefined' || !AgentUI.askWithPrompt) return;
        AgentUI.askWithPrompt(
            'Help me set up a routine — something Anjadhe does for me on its own. ' +
            'Walk me through it one question at a time: what it should do, when it should run, ' +
            'and whether it writes me an answer or takes actions.',
            { newChat: true }
        );
    },

    // --- Data (all reads go through the notes blob — storage source of truth) ---

    _prompts() {
        const list = NotePrompts.list();
        return list.sort((a, b) =>
            new Date(b.modifiedAt || 0).getTime() - new Date(a.modifiedAt || 0).getTime());
    },

    _note(id) {
        return NotePrompts.list().find(n => n.id === id) || null;
    },

    /** Feed posts generated by this prompt, newest first. */
    _outputs(promptId) {
        const d = StorageManager.get('notes');
        const notes = (d && Array.isArray(d.notes)) ? d.notes : [];
        return notes
            .filter(n => NoteTemplates.resolve(n) === 'feed' && n.feed && n.feed.promptId === promptId)
            .sort((a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0));
    },

    /** R4 observability: everything the engine knows about one routine. */
    _status(id) {
        return (typeof RoutineEngine !== 'undefined')
            ? RoutineEngine.statusFor(id)
            : { lastCheckedAt: null, lastMatchedAt: null, lastRun: null, lastError: null, queued: 0 };
    },

    _ago(iso) {
        return (iso && typeof PromptFeed !== 'undefined') ? PromptFeed._timeAgo(iso) : null;
    },

    _lastRunLabel(p) {
        const last = this._status(p.id).lastRun;
        return last ? `ran ${this._ago(last)}` : 'not run yet';
    },

    _chips(cfg) {
        return [
            cfg.offline
                ? `<span class="prompt-mgr-chip">${UIUtils.escapeHtml(NotePrompts.scheduleLabel(cfg))}</span>`
                : `<span class="prompt-mgr-chip">${cfg.target === 'browser' ? 'runs in Browser' : 'runs in Assistant'}</span>`,
            cfg.web ? '<span class="prompt-mgr-chip">&#127760; web</span>' : '',
            cfg.useContext ? '<span class="prompt-mgr-chip">&#10024; my context</span>' : ''
        ].filter(Boolean).join('');
    },

    // --- Render ---

    // Deep-link to one prompt's detail page — used by the assistant's record
    // pills ("Prompt · Market Close Review" under an answer) and any other
    // cross-app link. Safe before init: render() falls back to the list if
    // the id is unknown.
    openPrompt(id) {
        this._view = 'detail';
        this._openId = id;
        this.render();
    },

    render() {
        const container = document.getElementById('prompts-main');
        if (!container) return;
        // The open prompt may have been deleted (or synced away).
        if (this._openId && !this._note(this._openId)) {
            this._view = 'list';
            this._openId = null;
        }
        this._renderCrumbs();
        this._renderWaiting();
        if (this._view === 'form') this._renderForm(container, this._openId ? this._note(this._openId) : null);
        else if (this._view === 'detail') this._renderDetail(container, this._note(this._openId));
        else this._renderList(container);
    },

    /**
     * The page title, through Breadcrumb like every other app page. It used
     * to be a bare text node in index.html, which meant it missed the
     * `.breadcrumb-current` styling every other title gets (600 weight, and
     * the padding that puts the first glyph on the shared left edge) — so
     * this one page's heading sat lighter and 8px to the left of Actions,
     * Notes and the rest. The trail also names where you are inside the app,
     * which is what the detail and form states were missing.
     */
    _renderCrumbs() {
        if (typeof Breadcrumb === 'undefined') return;
        const toList = () => { this._view = 'list'; this._openId = null; this.render(); };
        const note = this._openId ? this._note(this._openId) : null;
        if (this._view === 'detail' && note) {
            Breadcrumb.render('prompts-breadcrumb', [
                { label: 'Routines', action: toList },
                { label: note.title || 'Untitled routine' }
            ]);
        } else if (this._view === 'form') {
            Breadcrumb.render('prompts-breadcrumb', [
                { label: 'Routines', action: toList },
                { label: note ? 'Edit routine' : 'New routine' }
            ]);
        } else {
            Breadcrumb.render('prompts-breadcrumb', [{ label: 'Routines' }]);
        }
    },

    /**
     * C10: "Waiting on you" — task-mode runs that stopped at an approval
     * while nobody was here. It sits ABOVE the routines list on every view of
     * this page, because it is the only thing here that is blocked on the
     * user; everything else is either running or idle.
     *
     * Resuming from here is a human decision, so TaskService marks the run
     * attended and its next `ask` opens the normal dialog instead of pausing
     * again.
     */
    _renderWaiting() {
        const section = document.getElementById('prompts-waiting-section');
        const box = document.getElementById('prompts-waiting');
        if (!section || !box) return;
        if (typeof TaskService === 'undefined' || typeof TaskService._all !== 'function') {
            section.hidden = true;
            return;
        }
        const waiting = TaskService._all().filter(t => t && ['awaiting_user', 'paused'].includes(t.status));
        section.hidden = waiting.length === 0;
        if (!waiting.length) return;
        const esc = UIUtils.escapeHtml;
        const countEl = document.getElementById('prompts-waiting-count');
        if (countEl) countEl.textContent = waiting.length > 0 ? String(waiting.length) : '';
        box.innerHTML = waiting.map(t => `
            <div class="routines-waiting-row" data-task="${esc(t.id)}">
                <div class="routines-waiting-main">
                    <div class="routines-waiting-title">${esc(t.goal)}</div>
                    <div class="routines-waiting-sub">${esc(t.note || t.status)}</div>
                </div>
                <span class="routines-waiting-actions">
                    <button class="secondary-btn routines-act" data-act="${t.status === 'paused' ? 'resume' : 'approve'}" type="button">${t.status === 'paused' ? 'Resume' : 'Review &amp; run'}</button>
                    <button class="secondary-btn routines-act" data-act="cancel" type="button">Cancel</button>
                </span>
            </div>`).join('');
        box.onclick = async (e) => {
            const btn = e.target.closest('button[data-act]');
            if (!btn) return;
            const id = btn.closest('[data-task]')?.dataset.task;
            if (!id) return;
            const act = btn.dataset.act;
            if (act === 'resume') await TaskService.resume(id);
            else if (act === 'approve') await TaskService.approve(id);
            else if (act === 'cancel') TaskService.cancel(id);
            this.render();
        };
    },

    // Table sort: which columns open ascending on first click.
    _TEXT_COLS: ['title', 'schedule'],

    _tableSort() {
        if (!this._table.sort) {
            let stored = null;
            try { stored = JSON.parse(localStorage.getItem('routines-sort') || 'null'); } catch (e) { /* default stands */ }
            this._table.sort = (stored && stored.col) ? stored : { col: 'schedule', dir: 'asc' };
        }
        return this._table.sort;
    },

    _setTableSort(col) {
        const s = this._tableSort();
        if (s.col === col) s.dir = s.dir === 'asc' ? 'desc' : 'asc';
        else { s.col = col; s.dir = this._TEXT_COLS.includes(col) ? 'asc' : 'desc'; }
        try { localStorage.setItem('routines-sort', JSON.stringify(s)); } catch (e) { /* ignore */ }
        this.render();
    },

    _renderList(container) {
        // Routines only — saved (non-scheduled) prompt notes live in Notes.
        const all = this._prompts().filter(p => NotePrompts.config(p).offline);
        const esc = UIUtils.escapeHtml;

        if (!all.length) {
            container.innerHTML = `
                <div class="prompt-mgr-list prompts-page-list">
                    <div class="prompt-mgr-empty">
                        <span class="prompt-mgr-empty-icon" aria-hidden="true">&#9201;</span>
                        <p class="prompt-mgr-empty-text">No routines yet. A routine runs a prompt on a schedule<br>and posts each result to your Home feed.</p>
                        <button class="ask-prompt-btn primary routines-ask-ai" type="button">&ldquo;Help me set up a routine&rdquo;</button>
                        <button class="secondary-btn prompt-mgr-empty-add" type="button">Create one by hand</button>
                    </div>
                </div>`;
            container.querySelector('.prompt-mgr-empty-add')?.addEventListener('click', () => {
                this._view = 'form'; this._openId = null; this.render();
            });
            container.querySelector('.routines-ask-ai')?.addEventListener('click', () => this.askNewRoutine());
            return;
        }

        const t = this._table;
        const sort = this._tableSort();
        const runs = (typeof RoutineEngine !== 'undefined' && RoutineEngine.state.runs) || {};

        let rows = all.map(p => {
            const cfg = NotePrompts.config(p);
            return { p, cfg, body: NotePrompts.bodyText(p), last: runs[p.id] || null };
        });
        const q = t.q.trim().toLowerCase();
        if (q) rows = rows.filter(r =>
            (r.p.title || '').toLowerCase().includes(q) || r.body.toLowerCase().includes(q));
        if (t.interval !== 'all') rows = rows.filter(r => r.cfg.interval === t.interval);

        const ORDER = { hourly: 0, '6h': 1, daily: 2, weekdays: 3, weekly: 4 };
        const dir = sort.dir === 'asc' ? 1 : -1;
        const cmp = {
            title: (a, b) => (a.p.title || '').localeCompare(b.p.title || ''),
            schedule: (a, b) => (ORDER[a.cfg.interval] - ORDER[b.cfg.interval])
                || String(a.cfg.time || '99:99').localeCompare(String(b.cfg.time || '99:99')),
            web: (a, b) => (a.cfg.web ? 1 : 0) - (b.cfg.web ? 1 : 0),
            context: (a, b) => (a.cfg.useContext ? 1 : 0) - (b.cfg.useContext ? 1 : 0),
            lastRun: (a, b) => (Date.parse(a.last) || 0) - (Date.parse(b.last) || 0)
        }[sort.col] || (() => 0);
        rows.sort((a, b) => dir * cmp(a, b) || (a.p.title || '').localeCompare(b.p.title || ''));

        const th = (col, label, cls = '') => {
            const active = sort.col === col;
            const arrow = active ? (sort.dir === 'asc' ? '&#9650;' : '&#9660;') : '';
            return `<th class="routines-th ${cls}" data-col="${col}" role="button" tabindex="0"
                        aria-sort="${active ? (sort.dir === 'asc' ? 'ascending' : 'descending') : 'none'}"
                    >${label}${arrow ? `<span class="routines-sort-arrow">${arrow}</span>` : ''}</th>`;
        };
        const errors = (typeof RoutineEngine !== 'undefined' && RoutineEngine.state.errors) || {};
        const tr = (r) => `
            <tr class="routines-row" data-open-prompt="${esc(r.p.id)}" tabindex="0">
                <td class="routines-td-title" title="${esc(r.p.title || 'Untitled routine')}">
                    <span class="routines-td-title-text">${esc(r.p.title || 'Untitled routine')}</span>
                    ${r.cfg.runMode === 'task' ? '<span class="routines-mode-chip" title="This routine can make changes">acts</span>' : ''}
                    ${errors[r.p.id] ? `<span class="routines-err-chip" title="${esc(errors[r.p.id])}">needs attention</span>` : ''}
                </td>
                <td class="routines-td-sched">${esc(NotePrompts.triggerLabel(r.cfg))}</td>
                <td class="routines-td-flag">${r.cfg.web ? '&#10003;' : ''}</td>
                <td class="routines-td-flag">${r.cfg.useContext ? '&#10003;' : ''}</td>
                <td class="routines-td-ran">${r.last && typeof PromptFeed !== 'undefined' ? esc(PromptFeed._timeAgo(r.last)) : 'never'}</td>
                <td class="routines-td-actions">
                    <button class="prompt-mgr-iconbtn" data-run="${esc(r.p.id)}" type="button" title="Run now" aria-label="Run now">&#9654;</button>
                    <button class="prompt-mgr-iconbtn" data-edit="${esc(r.p.id)}" type="button" title="Edit" aria-label="Edit">&#9998;</button>
                    <button class="prompt-mgr-iconbtn prompt-mgr-del" data-del="${esc(r.p.id)}" type="button" title="Delete" aria-label="Delete">&#128465;</button>
                </td>
            </tr>`;

        const INTERVALS = [['all', 'All schedules'], ['hourly', 'Hourly'], ['6h', 'Every 6h'],
                           ['daily', 'Daily'], ['weekdays', 'Weekdays'], ['weekly', 'Weekly']];
        container.innerHTML = `
            <div class="routines-toolbar">
                <input id="routines-search" class="routines-search" type="search"
                       placeholder="Search routines" value="${esc(t.q)}" spellcheck="false">
                <select id="routines-filter" class="routines-filter" aria-label="Filter by schedule">
                    ${INTERVALS.map(([v, l]) => `<option value="${v}" ${t.interval === v ? 'selected' : ''}>${l}</option>`).join('')}
                </select>
                <span class="routines-count">${rows.length} of ${all.length}</span>
            </div>
            <table class="routines-table">
                <thead><tr>
                    ${th('title', 'Routine')}
                    ${th('schedule', 'Runs when')}
                    ${th('web', 'Web', 'routines-th-flag')}
                    ${th('context', 'Context', 'routines-th-flag')}
                    ${th('lastRun', 'Last run')}
                    <th class="routines-th-actions"></th>
                </tr></thead>
                <tbody>
                    ${rows.length ? rows.map(tr).join('')
                        : `<tr><td class="routines-table-empty" colspan="6">No routines match.</td></tr>`}
                </tbody>
            </table>`;

        // Search re-renders the table on each keystroke; the input is
        // rebuilt with it, so focus and caret are put back by hand.
        const search = container.querySelector('#routines-search');
        search.addEventListener('input', () => {
            this._table.q = search.value;
            const pos = search.selectionStart;
            this._renderList(container);
            const again = container.querySelector('#routines-search');
            again.focus();
            try { again.setSelectionRange(pos, pos); } catch (e) { /* type=search quirk */ }
        });
        container.querySelector('#routines-filter').addEventListener('change', (e) => {
            this._table.interval = e.target.value;
            this._renderList(container);
        });
        container.querySelectorAll('th[data-col]').forEach(h => {
            h.addEventListener('click', () => this._setTableSort(h.dataset.col));
            h.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); this._setTableSort(h.dataset.col); }
            });
        });
        container.querySelectorAll('[data-open-prompt]').forEach(row => {
            row.addEventListener('click', (e) => {
                if (e.target.closest('button')) return;
                this._view = 'detail'; this._openId = row.dataset.openPrompt; this.render();
            });
            row.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' && !e.target.closest('button')) {
                    this._view = 'detail'; this._openId = row.dataset.openPrompt; this.render();
                }
            });
        });
        container.querySelectorAll('[data-run]').forEach(b =>
            b.addEventListener('click', () => this._runNow(b.dataset.run, b)));
        container.querySelectorAll('[data-edit]').forEach(b =>
            b.addEventListener('click', () => {
                this._view = 'form'; this._openId = b.dataset.edit; this.render();
            }));
        container.querySelectorAll('[data-del]').forEach(b =>
            b.addEventListener('click', () => this._delete(b.dataset.del)));
    },

    _renderDetail(container, note) {
        if (!note) { this._view = 'list'; this._renderList(container); return; }
        const cfg = NotePrompts.config(note);
        const body = NotePrompts.bodyText(note);
        const outputs = this._outputs(note.id).slice(0, 20);
        const esc = UIUtils.escapeHtml;

        const postRows = outputs.map(o => {
            const when = o.createdAt
                ? new Date(o.createdAt).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
                : '';
            const tmp = document.createElement('div');
            tmp.innerHTML = o.content || '';
            const text = o.feed && o.feed.error
                ? o.feed.error
                : (tmp.textContent || '').replace(/\s+/g, ' ').trim();
            const preview = text.length > 160 ? text.slice(0, 160).trimEnd() + '…' : text;
            return `
                <button class="routines-post-row${o.feed && o.feed.error ? ' is-error' : ''}" data-open-post="${o.id}" type="button">
                    <span class="routines-post-when">${when}</span>
                    <span class="routines-post-preview">${esc(preview)}</span>
                </button>`;
        }).join('');

        // An action routine's runs, newest first — the execution log lives
        // HERE, on the routine, never on the home feed (2026-08-03): the
        // feed is a reading surface for content, and a step transcript is a
        // log. Each run is the task record the engine already keeps, with
        // the compiled report TaskService._report stored on it.
        const runs = (cfg.runMode === 'task' && typeof TaskService !== 'undefined')
            ? (TaskService._all() || []).filter(t => t && t.routineId === note.id
                && (t.status === 'done' || t.status === 'failed')).slice(0, 20)
            : [];
        const runRows = runs.map(t => {
            const when = t.updatedAt
                ? new Date(t.updatedAt).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
                : '';
            const ok = t.status === 'done';
            return `
                <details class="routines-run${ok ? '' : ' is-error'}">
                    <summary class="routines-run-row">
                        <span class="routines-run-mark">${ok ? '&#10003;' : '&#10007;'}</span>
                        <span class="routines-post-when">${when}</span>
                        <span class="routines-post-preview">${esc(t.note || (ok ? 'Done.' : 'Did not finish.'))}</span>
                    </summary>
                    <pre class="routines-run-report">${esc(t.report || t.activity || 'No log was recorded for this run.')}</pre>
                </details>`;
        }).join('');

        // What the routine draws on, as one quiet value line.
        const uses = [cfg.web ? 'Web search' : '', cfg.useContext ? 'My context' : '']
            .filter(Boolean).join(' &middot; ');
        const scheduleValue = cfg.offline
            ? esc(NotePrompts.triggerLabel(cfg))
            : (cfg.target === 'browser' ? 'runs in Browser' : 'runs in Assistant');
        // C10: what this routine is allowed to DO, stated rather than implied.
        // "Can it change my data" is the question the merge made worth asking
        // on every routine, because the answer is no longer given by which
        // page you found it on.
        const modeValue = cfg.runMode === 'task'
            ? 'Takes actions &mdash; can change things, and pauses for permission'
            : 'Writes an answer &mdash; cannot change anything';
        const status = this._status(note.id);
        const lastError = status.lastError || '';
        // R4 (D4/T6): "nothing matched" and "this has been broken since the
        // day you armed it" looked identical, which is the only reason the D0
        // outage survived from C8.5 through C10. A checked stamp that is
        // absent says the engine has never evaluated this routine at all —
        // a different problem from one that evaluates and never matches.
        const checkedLabel = status.lastCheckedAt
            ? this._ago(status.lastCheckedAt)
            : 'not yet — the engine has not evaluated this routine';
        const matchedLabel = status.lastMatchedAt
            ? this._ago(status.lastMatchedAt)
            : (status.lastCheckedAt ? 'never matched anything yet' : 'never');
        // Only worth showing when it is NOT this Mac: naming the local
        // machine on every routine is noise on a single-Mac install.
        const elsewhere = cfg.homeMachineId
            && typeof RoutineEngine !== 'undefined' && RoutineEngine._machineId
            && cfg.homeMachineId !== RoutineEngine._machineId;
        const prop = (label, value) => `
            <div class="routines-prop">
                <span class="routines-prop-label">${label}</span>
                <span class="routines-prop-value">${value}</span>
            </div>`;

        container.innerHTML = `
            <div class="routines-detail-head">
                <h3 class="routines-detail-title">${esc(note.title || 'Untitled routine')}</h3>
                <div class="routines-detail-actions">
                    <button class="secondary-btn routines-act" data-run="${note.id}" type="button" title="Run this routine now">&#9654; Run now</button>
                    ${cfg.offline ? `<button class="secondary-btn routines-act" data-test="${note.id}" type="button" title="See what this trigger would fire on right now — nothing runs, nothing is recorded">Test trigger</button>` : ''}
                    <button class="secondary-btn routines-act" data-edit="${note.id}" type="button">Edit</button>
                    <button class="secondary-btn routines-act routines-act-delete" data-del="${note.id}" type="button">Delete</button>
                </div>
            </div>
            <div class="routines-props">
                ${prop('Runs when', scheduleValue)}
                ${cfg.offline ? prop('Does', modeValue) : ''}
                ${uses ? prop('Uses', uses) : ''}
                ${cfg.offline ? prop('Last run', esc(this._lastRunLabel(note))) : ''}
                ${cfg.offline ? prop('Last checked', esc(checkedLabel)) : ''}
                ${cfg.offline ? prop('Last matched', esc(matchedLabel)) : ''}
                ${status.queued ? prop('Queued', `${status.queued} run${status.queued > 1 ? 's' : ''} waiting for the task slot`) : ''}
                ${elsewhere ? prop('Runs on', 'Another Mac &mdash; it is armed there, not here') : ''}
                ${lastError ? prop('Last problem', `<span class="routines-err-text">${esc(lastError)}</span>`) : ''}
            </div>
            <div class="routines-trigtest" hidden></div>
            <div class="routines-prompt-section">
                <div class="detail-section-header">Prompt</div>
                <div class="routines-prompt-text">${esc(body) || '<span class="routines-empty">No prompt text yet — edit to add one.</span>'}</div>
            </div>
            ${runRows ? `
                <div class="routines-outputs">
                    <div class="detail-section-header">Run history</div>
                    ${runRows}
                </div>` : ''}
            ${outputs.length ? `
                <div class="routines-outputs">
                    <div class="detail-section-header">Feed posts</div>
                    ${postRows}
                </div>` : ''}
            ${!runRows && !outputs.length && cfg.offline ? `<p class="routines-empty">${cfg.runMode === 'task'
                ? 'No runs yet — each run&rsquo;s log will appear here.'
                : 'No runs yet — results will appear here and on your Home feed.'}</p>` : ''}
        `;

        container.querySelector('[data-run]')?.addEventListener('click', (e) => this._runNow(note.id, e.currentTarget));
        container.querySelector('[data-test]')?.addEventListener('click', (e) => this._testTrigger(note, e.currentTarget));
        container.querySelector('[data-edit]')?.addEventListener('click', () => {
            this._view = 'form'; this.render();
        });
        container.querySelector('[data-del]')?.addEventListener('click', () => this._delete(note.id));
        container.querySelectorAll('[data-open-post]').forEach(b =>
            b.addEventListener('click', () => {
                if (typeof PromptFeed !== 'undefined' && PromptFeed.openPost) PromptFeed.openPost(b.dataset.openPost);
            }));
    },

    _renderForm(container, note) {
        const cfg = note ? NotePrompts.config(note) : NotePrompts.config({ prompt: { ...NotePrompts.DEFAULTS } });
        const title = note ? (note.title || '') : '';
        const body = note ? NotePrompts.bodyText(note) : '';
        const esc0 = UIUtils.escapeHtml;
        // C10: one form for all three triggers. The panes are all in the DOM
        // and toggled by `hidden`, so switching type never loses what was
        // typed into another one.
        const trig = cfg.trigger || { type: 'time' };
        const trigType = trig.type || 'time';

        container.innerHTML = `
            <div class="routines-form">
                ${!note ? `
                <!-- Creation is a conversation first (the goals pattern): the
                     pill opens the assistant's routine interview, which knows
                     what routines can do and asks one question at a time. The
                     form below stays first-class for people who know what
                     they want. -->
                <div class="routines-ask-row">
                    <button type="button" class="ask-prompt-btn primary routines-ask-ai">&ldquo;Help me set up a routine&rdquo;</button>
                    <span class="routines-ask-or">or fill it in yourself:</span>
                </div>` : ''}
                <input id="prompt-mgr-title" class="detail-title-input routines-title-input" type="text"
                       placeholder="Name this routine..." value="${UIUtils.escapeHtml(title)}" autocomplete="off" spellcheck="false">

                <div class="detail-section-header">Prompt</div>
                <textarea id="prompt-mgr-body" class="routines-body-input" rows="4"
                          placeholder="What should run on each schedule? Write it as a request to your assistant.">${UIUtils.escapeHtml(body)}</textarea>

                <div class="routines-props routines-form-props">
                    <input type="hidden" id="prompt-mgr-interval" value="${cfg.interval}">
                    <input type="hidden" id="prompt-mgr-trigtype" value="${trigType}">
                    <input type="hidden" id="prompt-mgr-runmode" value="${cfg.runMode}">

                    <div class="routines-prop">
                        <span class="routines-prop-label">Runs when</span>
                        <div class="prompt-mgr-seg" role="group" aria-label="What starts this routine">
                            ${[['time', 'On a schedule'], ['email', 'An email arrives'], ['file', 'A file appears']].map(([v, l]) => `
                                <button type="button" class="prompt-mgr-seg-btn prompt-mgr-trig-btn ${trigType === v ? 'active' : ''}" data-trig="${v}" aria-pressed="${trigType === v}">${l}</button>`).join('')}
                        </div>
                    </div>

                    <div class="routines-trig-pane" data-trig-pane="time" ${trigType === 'time' ? '' : 'hidden'}>
                        <div class="routines-prop">
                            <span class="routines-prop-label">Every</span>
                            <div class="prompt-mgr-seg" role="group" aria-label="Run every">
                                ${['hourly', '6h', 'daily', 'weekdays', 'weekly'].map(v => `
                                    <button type="button" class="prompt-mgr-seg-btn ${cfg.interval === v ? 'active' : ''}" data-value="${v}" aria-pressed="${cfg.interval === v}">${NotePrompts.intervalLabel(v)}</button>`).join('')}
                            </div>
                        </div>
                        <div class="routines-prop prompt-mgr-time-row" ${['daily', 'weekdays', 'weekly'].includes(cfg.interval) ? '' : 'hidden'}>
                            <label class="routines-prop-label" for="prompt-mgr-time">At</label>
                            <input type="time" id="prompt-mgr-time" class="routines-time" value="${cfg.time || ''}">
                        </div>
                    </div>

                    <div class="routines-trig-pane" data-trig-pane="email" ${trigType === 'email' ? '' : 'hidden'}>
                        <div class="routines-prop">
                            <label class="routines-prop-label" for="prompt-mgr-trig-from">From contains</label>
                            <input type="text" id="prompt-mgr-trig-from" class="routines-trig-input"
                                   placeholder="billing@acme.com" value="${esc0(trig.from || '')}" spellcheck="false">
                        </div>
                        <div class="routines-prop">
                            <label class="routines-prop-label" for="prompt-mgr-trig-subject">Subject contains</label>
                            <input type="text" id="prompt-mgr-trig-subject" class="routines-trig-input"
                                   placeholder="invoice" value="${esc0(trig.subject || '')}" spellcheck="false">
                        </div>
                        <div class="routines-prop">
                            <label class="routines-prop-label" for="prompt-mgr-trig-contains">Message contains</label>
                            <input type="text" id="prompt-mgr-trig-contains" class="routines-trig-input"
                                   placeholder="invoice" value="${esc0(trig.contains || '')}" spellcheck="false">
                        </div>
                        <p class="routines-form-hint">Fill in at least one. &ldquo;Message contains&rdquo; searches the whole email, not just the subject line. Checked against mail already fetched to this Mac.</p>
                    </div>

                    <div class="routines-trig-pane" data-trig-pane="file" ${trigType === 'file' ? '' : 'hidden'}>
                        <div class="routines-prop">
                            <label class="routines-prop-label" for="prompt-mgr-trig-folder">Folder</label>
                            <input type="text" id="prompt-mgr-trig-folder" class="routines-trig-input"
                                   placeholder="~/Downloads" value="${esc0(trig.folder || '')}" spellcheck="false">
                        </div>
                        <div class="routines-prop">
                            <label class="routines-prop-label" for="prompt-mgr-trig-pattern">Matching</label>
                            <input type="text" id="prompt-mgr-trig-pattern" class="routines-trig-input"
                                   placeholder="*.pdf (optional)" value="${esc0(trig.pattern || '')}" spellcheck="false">
                        </div>
                        <p class="routines-form-hint">The folder has to be one you have already let the assistant read.</p>
                    </div>

                    <div class="routines-prop">
                        <span class="routines-prop-label">Does</span>
                        <div class="prompt-mgr-seg" role="group" aria-label="What this routine may do">
                            ${[['digest', 'Writes me an answer'], ['task', 'Takes actions']].map(([v, l]) => `
                                <button type="button" class="prompt-mgr-seg-btn prompt-mgr-mode-btn ${cfg.runMode === v ? 'active' : ''}" data-mode="${v}" aria-pressed="${cfg.runMode === v}">${l}</button>`).join('')}
                        </div>
                    </div>

                    <div class="routines-prop routines-uses-row" ${cfg.runMode === 'task' ? 'hidden' : ''}>
                        <span class="routines-prop-label">Uses</span>
                        <div class="routines-uses">
                            <label class="prompt-mgr-optchip" title="Let the model search the web during the run">
                                <input type="checkbox" id="prompt-mgr-web" ${cfg.web ? 'checked' : ''}>
                                <span>&#127760; Web search</span>
                            </label>
                            <label class="prompt-mgr-optchip" title="Run through the AI Assistant with your memory, goals, and schedule">
                                <input type="checkbox" id="prompt-mgr-context" ${cfg.useContext ? 'checked' : ''}>
                                <span>&#10024; My context</span>
                            </label>
                        </div>
                    </div>
                </div>
                <p class="routines-form-hint routines-mode-hint">${cfg.runMode === 'task'
                    ? 'Runs a multi-step task on its own. It can change your data; any step needing permission pauses and notifies you. Each run keeps its log here, under Run history.'
                    : 'Runs on your local model and posts each result to the Home feed. It cannot change anything.'}</p>

                <div class="routines-form-actions">
                    <button class="secondary-btn prompt-mgr-cancel" type="button">Cancel</button>
                    <button class="primary-btn prompt-mgr-save" type="button">${note ? 'Save changes' : 'Create routine'}</button>
                </div>
            </div>`;

        const back = () => {
            this._view = this._openId ? 'detail' : 'list';
            this.render();
        };
        container.querySelector('.prompt-mgr-cancel')?.addEventListener('click', back);

        container.querySelector('.routines-ask-ai')?.addEventListener('click', () => this.askNewRoutine());

        // Each segmented control writes into its own hidden input so the save
        // handler reads plain fields (same recipe as the old modal form).
        // NOTE the selectors are scoped per group: there are three segmented
        // controls on this form now, and one shared `.prompt-mgr-seg-btn`
        // handler would have every click rewrite the interval.
        const pressGroup = (buttons, chosen) => buttons.forEach(x => {
            x.classList.toggle('active', x === chosen);
            x.setAttribute('aria-pressed', String(x === chosen));
        });

        const intervalBtns = [...container.querySelectorAll('[data-trig-pane="time"] .prompt-mgr-seg-btn[data-value]')];
        intervalBtns.forEach(b => b.addEventListener('click', () => {
            container.querySelector('#prompt-mgr-interval').value = b.dataset.value;
            pressGroup(intervalBtns, b);
            // A run time only makes sense for wall-clock intervals.
            container.querySelector('.prompt-mgr-time-row').hidden =
                !['daily', 'weekdays', 'weekly'].includes(b.dataset.value);
        }));

        const trigBtns = [...container.querySelectorAll('.prompt-mgr-trig-btn')];
        trigBtns.forEach(b => b.addEventListener('click', () => {
            container.querySelector('#prompt-mgr-trigtype').value = b.dataset.trig;
            pressGroup(trigBtns, b);
            container.querySelectorAll('[data-trig-pane]').forEach(p => {
                p.hidden = p.dataset.trigPane !== b.dataset.trig;
            });
        }));

        // Switching to "Takes actions" hides web/context: those options
        // belong to the single-turn digest path, and a task run decides its
        // own tools.
        const modeBtns = [...container.querySelectorAll('.prompt-mgr-mode-btn')];
        modeBtns.forEach(b => b.addEventListener('click', () => {
            container.querySelector('#prompt-mgr-runmode').value = b.dataset.mode;
            pressGroup(modeBtns, b);
            const isTask = b.dataset.mode === 'task';
            const usesRow = container.querySelector('.routines-uses-row');
            if (usesRow) usesRow.hidden = isTask;
            const hint = container.querySelector('.routines-mode-hint');
            if (hint) {
                hint.textContent = isTask
                    ? 'Runs a multi-step task on its own. It can change your data; any step needing permission pauses and notifies you. Each run keeps its log here, under Run history.'
                    : 'Runs on your local model and posts each result to the Home feed. It cannot change anything.';
            }
        }));

        // Cmd/Ctrl+Enter from the prompt body saves — same muscle memory as
        // the assistant composer.
        container.querySelector('#prompt-mgr-body')?.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
                e.preventDefault();
                container.querySelector('.prompt-mgr-save')?.click();
            }
        });

        container.querySelector('.prompt-mgr-save')?.addEventListener('click', () => {
            const t = container.querySelector('#prompt-mgr-title').value.trim();
            const b = container.querySelector('#prompt-mgr-body').value.trim();
            if (!b) { UIUtils.showToast('Add a prompt first', 'error'); return; }
            const interval = container.querySelector('#prompt-mgr-interval').value;
            const trigType = container.querySelector('#prompt-mgr-trigtype').value;
            const runMode = container.querySelector('#prompt-mgr-runmode').value === 'task' ? 'task' : 'digest';

            // Build the trigger from the pane that is showing. Refuse an
            // empty rule rather than silently falling back to a schedule —
            // the fallback exists for READING old records, and using it here
            // would hand someone a daily routine they never asked for.
            let trigger;
            if (trigType === 'email') {
                const from = container.querySelector('#prompt-mgr-trig-from').value.trim();
                const subject = container.querySelector('#prompt-mgr-trig-subject').value.trim();
                const contains = container.querySelector('#prompt-mgr-trig-contains').value.trim();
                if (!from && !subject && !contains) {
                    UIUtils.showToast('Add a sender, subject or message text to match', 'error');
                    return;
                }
                trigger = { type: 'email', from, subject, contains };
            } else if (trigType === 'file') {
                const folder = container.querySelector('#prompt-mgr-trig-folder').value.trim();
                if (!folder) {
                    UIUtils.showToast('Add a folder to watch', 'error');
                    return;
                }
                trigger = { type: 'file', folder, pattern: container.querySelector('#prompt-mgr-trig-pattern').value.trim() };
            } else {
                trigger = { type: 'time', interval };
            }

            if (runMode === 'task' && (typeof FEATURES === 'undefined' || !FEATURES.isEnabled('taskmode'))) {
                UIUtils.showToast('Task mode is off — this routine can only write you an answer', 'error');
                return;
            }

            // Everything created or edited on this page is a routine; the
            // run target only matters for saved prompts (edited in Notes),
            // so an existing one is carried through untouched.
            const config = {
                target: cfg.target,
                offline: true,
                runMode,
                trigger,
                interval,
                time: trigType === 'time' && ['daily', 'weekdays', 'weekly'].includes(interval)
                    ? (container.querySelector('#prompt-mgr-time').value || null) : null,
                web: runMode === 'digest' && container.querySelector('#prompt-mgr-web').checked,
                useContext: runMode === 'digest' && container.querySelector('#prompt-mgr-context').checked,
                // Creating a routine HERE arms it on this Mac; editing one
                // leaves its existing home alone (that is what the detail
                // page's "runs on another Mac" line reports).
                homeMachineId: note ? cfg.homeMachineId
                    : ((typeof RoutineEngine !== 'undefined' && RoutineEngine._machineId) || null)
            };
            const saved = note
                ? NotePrompts.update(note.id, { title: t, body: b, config })
                : NotePrompts.create({ title: t, body: b, config });
            // Nudge the scheduler so a newly created/enabled routine runs
            // soon instead of waiting for the next poll.
            if (typeof RoutineEngine !== 'undefined') {
                RoutineEngine.onRoutinesChanged();
            }
            UIUtils.showToast(note ? 'Routine updated' : 'Routine created', 'success');
            this._view = 'detail';
            this._openId = saved ? saved.id : this._openId;
            this.render();
        });

        setTimeout(() => container.querySelector('#prompt-mgr-title')?.focus(), 0);
    },

    // --- Actions ---

    async _runNow(id, btn) {
        const note = this._note(id);
        if (!note) return;
        const cfg = NotePrompts.config(note);
        if (cfg.offline) {
            if (typeof PromptFeed === 'undefined' || !PromptFeed.runNow) return;
            if (btn) btn.disabled = true;
            await PromptFeed.runNow(id);
            this.render();
        } else {
            NotePrompts.runDefault(note);
        }
    },

    /**
     * R4 — "Test trigger". Reports what the matcher WOULD fire on, right
     * now, and stamps nothing: no run, no marker moved, no error recorded.
     * The cheapest thing in docs/ROUTINE_TRIGGERS.md's plan and the one that
     * would have caught D0 in under a minute.
     */
    async _testTrigger(note, btn) {
        const box = document.querySelector('#prompts-main .routines-trigtest');
        if (!box) return;
        const esc = UIUtils.escapeHtml;
        if (btn) btn.disabled = true;
        box.hidden = false;
        box.innerHTML = '<span class="routines-empty">Checking…</span>';
        let r;
        try { r = await RoutineEngine.testTrigger(note); }
        catch (e) { r = { error: e?.message || 'the check could not run' }; }
        if (btn) btn.disabled = false;

        const lines = [];
        if (r.error) {
            lines.push(`<span class="routines-err-text">Cannot check: ${esc(r.error)}</span>`);
        } else if (r.fired) {
            lines.push(`<strong>Would fire now.</strong> ${esc(r.suffix || 'The schedule slot is due.')}`);
            if (r.matches && r.matches.length > 1) {
                lines.push(`${r.matches.length} things match right now: ${esc(r.matches.slice(0, 5).join('; '))}${r.matches.length > 5 ? '…' : ''}`);
            }
        } else {
            lines.push('<strong>Would not fire now.</strong> Nothing matches since its last run.');
            if (r.scanned != null) {
                // `scanned` is the candidate window, not the whole mailbox:
                // mail since this routine was armed (R1's floor), or every
                // file in the watched folder.
                lines.push(r.type === 'email'
                    ? `${r.scanned} message${r.scanned === 1 ? '' : 's'} since this routine was armed ${r.scanned === 1 ? 'was' : 'were'} there to check.`
                    : `${r.scanned} file${r.scanned === 1 ? '' : 's'} in the watched folder ${r.scanned === 1 ? 'was' : 'were'} there to check.`);
            }
        }
        if (r.otherMachine) lines.push('This routine is armed on another Mac, so this one will not run it.');
        lines.push('<span class="routines-empty">Nothing was run and nothing was recorded.</span>');
        box.innerHTML = lines.map(l => `<p class="routines-trigtest-line">${l}</p>`).join('');
    },

    async _delete(id) {
        const note = this._note(id);
        const noun = note && NotePrompts.config(note).offline ? 'routine' : 'prompt';
        const ok = await UIUtils.confirm(
            `Delete ${noun}`,
            `Delete &ldquo;${UIUtils.escapeHtml(note?.title || `this ${noun}`)}&rdquo;? This removes the ${noun} and stops its scheduled runs. Past feed posts stay.`,
            '🗑️',
            { confirmText: 'Delete' }
        );
        if (!ok) return;
        NotePrompts.remove(id);
        if (typeof PromptFeed !== 'undefined' && PromptFeed.render) PromptFeed.render();
        if (this._openId === id) { this._view = 'list'; this._openId = null; }
        this.render();
    }
};

AppManager.register('prompts', PromptsApp);
