/**
 * Routines App — the standalone page for routines (scheduled prompts that
 * run in the background and post results to the Home feed).
 *
 * Since 2026-07-31 this page is routines-ONLY: non-scheduled prompt notes
 * ("saved prompts") live in the Notes app like any other note, with the
 * editor's prompt config panel. Scheduling a saved prompt there turns it
 * into a routine and moves it here; the app id stays 'prompts' so deep
 * links and tools keep working. The BACKEND IS UNCHANGED: a routine is
 * still a note in the shared `notes` blob, read and written through
 * NotePrompts — so sync, the assistant's scheduled-prompt tools, and the
 * PromptFeed scheduler keep working untouched. This file is UI only.
 *
 * Three in-page views:
 *  - list:   every routine
 *  - detail: one routine — body, config chips, actions, recent feed posts
 *  - form:   create/edit (always a routine; reuses the old modal's
 *            .prompt-mgr-* classes so the styling carries)
 *
 * Entry points: the launcher tile, Home feed's "Manage routines" button,
 * the feed post overlay's routine link (all via
 * AppManager.openApp('prompts') / PromptsApp.open()).
 */

/*
 * Folded into Chats (2026-10-06, the simplification, docs/VISION.md): there
 * is no Routines page, list or form any more. A routine is a STANDING chat:
 * the Chats page lists every routine with its trigger and last run
 * (SimpleExperience.renderHistory), this file keeps ONE routine's detail
 * (run history, Run now, Test trigger, the waiting approvals, Delete), and
 * every change to a routine is a conversation: Edit opens the routine's chat
 * (update_routine's diff dialog is the confirmation), "Set up a routine"
 * opens the interview (start_routine_interview → create_routine, whose ask
 * shows a dry run first, so nothing is armed untried).
 */
const PromptsApp = {
    _view: 'detail',    // the detail is the only view left
    _openId: null,
    _bound: false,

    init() {
        this._bound = true;
    },

    /** External entry: a routine's detail; with no id, the Chats page (where the routines are listed); `create` is the interview. */
    open(opts = {}) {
        if (opts.create) { this.askNewRoutine(); return; }
        if (!opts.id || !this._note(opts.id)) { this.toChats(); return; }
        this._view = 'detail'; this._openId = opts.id;
        AppManager.openApp('prompts');
        this.render();
    },

    /** The way back: the Chats page, Standing section. */
    toChats() {
        this._openId = null;
        if (typeof AppManager !== 'undefined') AppManager.openAppFromLauncher('conversations');
    },

    /** Change a routine in its chat (2026-10-06): update_routine's diff dialog is the confirmation. */
    askChange(id) {
        const note = this._note(id);
        if (!note || typeof AgentUI === 'undefined' || !AgentUI.askWithPrompt) return;
        AgentUI.askWithPrompt(`I want to change my routine "${note.title || 'Untitled routine'}". Ask me what should be different, then make the change.`,
            { newChat: true, todayKey: `routine:${id}`, recordKey: `prompts:${id}`, recordLabel: note.title || 'Untitled routine' });
    },

    /**
     * The "Help me set up a routine" prompt pill — opens the assistant's
     * routine interview (start_routine_interview; the goals pattern). The
     * pill's wording contains "routine" on purpose: that word is what ships
     * the prompts tool group into the turn.
     */
    askNewRoutine() {
        if (typeof AgentUI === 'undefined' || !AgentUI.askWithPrompt) return;
        AgentUI.askWithPrompt(
            'Help me set up a routine — something nenva does for me on its own. ' +
            'Walk me through it one question at a time: what it should do, when it should run, ' +
            'and whether it writes me an answer or takes actions.',
            { newChat: true }
        );
    },

    // --- Data (all reads go through the notes blob — storage source of truth) ---

    _prompts() {
        const list = NotePrompts.list();
        return list.sort((a, b) =>
            new Date(b.modifiedAt || 0).getTime() - new Date(a.modifiedAt || 0).getTime());
    },

    _note(id) {
        return NotePrompts.list().find(n => n.id === id) || null;
    },

    /** Feed posts generated by this prompt, newest first. */
    _outputs(promptId) {
        const d = StorageManager.get('notes');
        const notes = (d && Array.isArray(d.notes)) ? d.notes : [];
        return notes
            .filter(n => NoteTemplates.resolve(n) === 'feed' && n.feed && n.feed.promptId === promptId)
            .sort((a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0));
    },

    /** R4 observability: everything the engine knows about one routine. */
    _status(id) {
        return (typeof RoutineEngine !== 'undefined')
            ? RoutineEngine.statusFor(id)
            : { lastCheckedAt: null, lastMatchedAt: null, lastRun: null, lastError: null, queued: 0 };
    },

    _ago(iso) {
        return (iso && typeof PromptFeed !== 'undefined') ? PromptFeed._timeAgo(iso) : null;
    },

    /** "12 min" while this routine's digest run is in flight, else null. */
    _runningNow(id) {
        const cur = (typeof PromptFeed !== 'undefined') ? PromptFeed._current : null;
        if (!cur || cur.promptId !== id) return null;
        const mins = Math.round((Date.now() - cur.startedAt) / 60000);
        return mins < 1 ? 'under a minute' : `${mins} min`;
    },

    _lastRunLabel(p) {
        const last = this._status(p.id).lastRun;
        return last ? `ran ${this._ago(last)}` : 'not run yet';
    },

    _chips(cfg) {
        return [
            cfg.offline
                ? `<span class="prompt-mgr-chip">${UIUtils.escapeHtml(NotePrompts.scheduleLabel(cfg))}</span>`
                : `<span class="prompt-mgr-chip">${cfg.target === 'browser' ? 'runs as web search' : 'runs in Assistant'}</span>`,
            cfg.web ? '<span class="prompt-mgr-chip">&#127760; web</span>' : '',
            cfg.useContext ? '<span class="prompt-mgr-chip">&#10024; my context</span>' : ''
        ].filter(Boolean).join('');
    },

    // --- Render ---

    /* ── One detail, rendered wherever it is needed ──────────────────────
       The routine's page, opened OVER the post that its run produced —
       `docs/ROUTINES_UX.md`'s held item, in the form that does not need the
       held item's false assumption (one routine ↔ one series) to be true.

       It is the `embedEditor` law: there is ONE routine detail and ONE
       repaint path. `render()` paints into `_embedHost` when it is set, so
       every `this.render()` inside the detail's own handlers — Run now,
       Test trigger, the prune offer, a decision — repaints the embedded
       copy correctly without a single call site knowing where it lives.

       What is deliberately NOT embedded is the FORM: a full edit is a page
       job (U2's preview, the draft, the trigger line), so Edit leaves. ── */
    _embedHost: null,

    embedDetail(host, id) {
        if (!host || !this._note(id)) return false;
        this._embedHost = host;
        this._view = 'detail';
        this._openId = id;
        this.render();
        return true;
    },

    detachDetail() {
        if (!this._embedHost) return;
        this._embedHost = null;
        // Repaint the real page only if it is mounted — the user was on
        // Home when this opened, and the Routines view may never have been.
        if (document.getElementById('prompts-main')) this.render();
    },

    openPrompt(id) {
        this._view = 'detail';
        this._openId = id;
        this.render();
    },

    render() {
        // An embedded host shows ONE routine, and lets go the moment there
        // is not one. The check is HERE, before anything is painted,
        // because the callers that end an embed do not agree on what they
        // leave behind: `_delete` clears `_openId` before repainting, so a
        // guard keyed on "the open id vanished" never fired and the
        // Routines LIST was painted into a panel over a post.
        if (this._embedHost && !this._note(this._openId)) {
            this._embedHost = null;
            document.dispatchEvent(new CustomEvent('anjadhe:routine-embed-closed'));
        }
        const container = this._embedHost || document.getElementById('prompts-main');
        if (!container) return;
        // The open routine may have been deleted (or synced away): there is
        // no list here any more, the Chats page is where routines live.
        if (!this._openId || !this._note(this._openId)) {
            if (!this._embedHost && typeof AppManager !== 'undefined' && AppManager.currentApp === 'prompts') this.toChats();
            return;
        }
        this._view = 'detail';
        this._renderCrumbs();
        this._renderWaiting();
        this._renderDetail(container, this._note(this._openId));
    },

    /**
     * The page title, through Breadcrumb like every other app page. It used
     * to be a bare text node in index.html, which meant it missed the
     * `.breadcrumb-current` styling every other title gets (600 weight, and
     * the padding that puts the first glyph on the shared left edge) — so
     * this one page's heading sat lighter and 8px to the left of Actions,
     * Notes and the rest. The trail also names where you are inside the app,
     * which is what the detail and form states were missing.
     */
    _renderCrumbs() {
        if (typeof Breadcrumb === 'undefined') return;
        const note = this._openId ? this._note(this._openId) : null;
        Breadcrumb.render('prompts-breadcrumb', [
            { label: 'Chats', action: () => this.toChats() },
            { label: note ? (note.title || 'Untitled routine') : 'Routine' }
        ]);
    },

    /**
     * C10: "Waiting on you" — task-mode runs that stopped at an approval
     * while nobody was here. It sits ABOVE the routines list on every view of
     * this page, because it is the only thing here that is blocked on the
     * user; everything else is either running or idle.
     *
     * Answering here is the human decision a waiting routine job needs (TeamJobs J2); it marks the run
     * attended and its next `ask` opens the normal dialog instead of pausing
     * again.
     */
    _renderWaiting() {
        const section = document.getElementById('prompts-waiting-section');
        const box = document.getElementById('prompts-waiting');
        if (!section || !box) return;
        if (typeof TeamJobs === 'undefined') {
            section.hidden = true;
            return;
        }
        // A routine's team job waiting on an answer, or paused (2026-10-02).
        const waiting = TeamJobs.all().filter(t => t && t.engine === 'team' && t.routineId && ['awaiting_user', 'paused'].includes(t.status));
        section.hidden = waiting.length === 0;
        if (!waiting.length) return;
        const esc = UIUtils.escapeHtml;
        const countEl = document.getElementById('prompts-waiting-count');
        if (countEl) countEl.textContent = waiting.length > 0 ? String(waiting.length) : '';
        box.innerHTML = waiting.map(t => `
            <div class="routines-waiting-row" data-task="${esc(t.id)}">
                <div class="routines-waiting-main">
                    <div class="routines-waiting-title">${esc(TeamJobs.routineTitle(t.routineId))}</div>
                    <div class="routines-waiting-sub">${esc(t.note || t.status)}</div>
                </div>
                <span class="routines-waiting-actions">
                    ${t.status === 'paused'
                        ? '<button class="secondary-btn routines-act" data-act="resume" type="button">Continue</button>'
                        : '<button class="primary-btn routines-act" data-act="approve" type="button">Allow</button><button class="secondary-btn routines-act" data-act="deny" type="button">Don&rsquo;t allow</button>'}
                    <button class="secondary-btn routines-act" data-act="cancel" type="button">Stop</button>
                </span>
            </div>`).join('');
        box.onclick = async (e) => {
            const btn = e.target.closest('button[data-act]');
            if (!btn) return;
            const id = btn.closest('[data-task]')?.dataset.task;
            if (!id) return;
            const act = btn.dataset.act;
            if (act === 'resume') await TeamJobs.resume(id);
            else if (act === 'approve') TeamJobs.answer(id, true);
            else if (act === 'deny') TeamJobs.answer(id, false);
            else if (act === 'cancel') await TeamJobs.stop(id);
            this.render();
        };
    },

    _askPillsHtml(note, cfg, quietStreak) {
        if (typeof AgentUI === 'undefined' || !AgentUI.askWithPrompt) return '';
        const esc = UIUtils.escapeHtml;
        const title = note.title || 'this routine';
        const btn = (label, prompt) =>
            `<button type="button" class="ask-prompt-btn" data-ask="${esc(prompt)}">&ldquo;${esc(label)}&rdquo;</button>`;
        const ref = `the routine “${title}”`;
        const pills = [];

        if (cfg.interval !== 'weekly' && (cfg.trigger || {}).type === 'time') {
            pills.push(btn('Make it weekly', `Change ${ref} to run once a week instead.`));
        }
        pills.push(btn('Make it shorter', `Change ${ref} so its answers are much shorter — a few lines, the essentials only.`));
        // NOT "only tell me when there's something": since U3 every digest
        // already stays quiet on a run with nothing to say, and a pill
        // offering what the routine already does teaches the user it does
        // the opposite.
        if (cfg.runMode !== 'task' && !cfg.web) {
            pills.push(btn('Let it search the web',
                `Turn on web search for ${ref} so it can look things up while it runs.`));
        }
        // A routine that has been silent run after run is either working
        // perfectly on a quiet stretch or looking for something it can
        // never find, and the difference is a question about the prompt —
        // which is exactly what the streak line above says out loud.
        if (quietStreak >= this.QUIET_STREAK_HINT) {
            pills.push(btn('Why does it never find anything?',
                `${ref} has had nothing to report for its last ${quietStreak} runs. Read its prompt and tell me whether it is looking for something it can never find here, and what to change.`));
        }
        pills.push(btn('Change what it does…',
            `I want to change what ${ref} does. Ask me what should be different, then update it.`));
        return `<div class="routines-ask-row routines-detail-ask">${pills.join('')}</div>`;
    },

    /* ── Measured by whether it is read (docs/ROUTINES_UX.md U8) ─────────
       The list used to headline LAST RUN, which says a routine is alive,
       not that it is wanted. Nobody deletes a routine that quietly wastes
       a model call every morning; they just stop opening it — and the app
       has always known that and never said it.

       The app may SAY SO and OFFER to slow it down. It may never disarm a
       routine the user armed: deciding for them is the same class of
       mistake as letting a model decide a routine is safe. Declining is
       remembered (per-Mac — a nudge is a moment, and the other Mac's user
       has not been offered anything yet). ──────────────────────────────── */
    // Sorting and filtering earn their place at this many routines.
    LIST_DENSE_MIN: 20,
    RARELY_MIN_EDITIONS: 5,
    RARELY_MAX_RATIO: 0.2,
    PRUNE_DISMISS_KEY: 'routine-prune-dismissed',

    _readStats(id) {
        const r = (typeof PromptFeed !== 'undefined' && PromptFeed.readRate)
            ? PromptFeed.readRate(id) : { shown: 0, opened: 0 };
        return {
            ...r,
            rarely: r.shown >= this.RARELY_MIN_EDITIONS
                && (r.opened / r.shown) <= this.RARELY_MAX_RATIO
        };
    },

    _pruneDismissed() {
        try { return JSON.parse(localStorage.getItem(this.PRUNE_DISMISS_KEY) || '{}') || {}; }
        catch { return {}; }
    },

    _dismissPrune(id) {
        const d = this._pruneDismissed();
        d[id] = new Date().toISOString();
        try { localStorage.setItem(this.PRUNE_DISMISS_KEY, JSON.stringify(d)); } catch { /* private window */ }
    },

    // How many silent runs in a row are worth saying out loud on the
    // detail. Below this, silence is just a quiet week (U3).
    QUIET_STREAK_HINT: 5,

    _renderDetail(container, note) {
        if (!note) { this.toChats(); return; }
        const cfg = NotePrompts.config(note);
        const body = NotePrompts.bodyText(note);
        const outputs = this._outputs(note.id).slice(0, 20);
        const esc = UIUtils.escapeHtml;
        // Record links ([title](anjadhe://task/<id>)) in a run report become
        // clickable links even inside the <pre> — the log stays verbatim
        // otherwise. See RecordLinks.
        const linkify = (s) => (typeof RecordLinks !== 'undefined') ? RecordLinks.linkifyEscapedText(s) : s;

        // U3 (docs/ROUTINES_UX.md): runs that settled with nothing to say
        // post no edition, so the history has to carry them or "quiet" and
        // "never ran" look identical — which is exactly the confusion that
        // makes silence feel like breakage. Newest first, interleaved with
        // the posted editions by time.
        const quietRuns = (typeof RoutineEngine !== 'undefined' && RoutineEngine.quietRuns)
            ? RoutineEngine.quietRuns(note.id) : [];
        const quietStreak = (typeof RoutineEngine !== 'undefined' && RoutineEngine.quietStreak)
            ? RoutineEngine.quietStreak(note.id, (outputs[0] || {}).createdAt || null) : 0;
        // U8: the offer to slow it down or stop it. The app asks; the user
        // decides; declining is remembered. A routine going quiet is NOT
        // the same as one being ignored — a run with nothing to report was
        // never shown, so it cannot have been skipped, and offering to
        // delete a routine that is working perfectly on a quiet stretch is
        // the worst version of this feature.
        const stats = this._readStats(note.id);
        const offerPrune = cfg.offline && stats.rarely && !quietStreak && !this._pruneDismissed()[note.id];

        const postRows = outputs.map(o => {
            const when = o.createdAt
                ? new Date(o.createdAt).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
                : '';
            const tmp = document.createElement('div');
            tmp.innerHTML = o.content || '';
            const text = o.feed && o.feed.error
                ? o.feed.error
                : (tmp.textContent || '').replace(/\s+/g, ' ').trim();
            const preview = text.length > 160 ? text.slice(0, 160).trimEnd() + '…' : text;
            return {
                at: o.createdAt || '',
                html: `
                <button class="routines-post-row${o.feed && o.feed.error ? ' is-error' : ''}" data-open-post="${o.id}" type="button">
                    <span class="routines-post-when">${when}</span>
                    <span class="routines-post-preview">${esc(preview)}</span>
                </button>`
            };
        }).concat(quietRuns.map(q => {
            const when = q.at
                ? new Date(q.at).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
                : '';
            // Not a button: there is nothing to open. A quiet run is a
            // successful run, so it wears no error styling either.
            return {
                at: q.at || '',
                html: `
                <div class="routines-post-row is-quiet">
                    <span class="routines-post-when">${when}</span>
                    <span class="routines-post-preview">Nothing to report${q.reason ? ' &middot; ' + esc(q.reason) : ''}</span>
                </div>`
            };
        })).sort((a, b) => (Date.parse(b.at) || 0) - (Date.parse(a.at) || 0))
          .slice(0, 20).map(r => r.html).join('');

        // An action routine's runs, newest first — the execution log lives
        // HERE, on the routine, never on the home feed (2026-08-03): the
        // feed is a reading surface for content, and a step transcript is a
        // log. Each run is the task record the engine already keeps, with
        // its report, built by TeamJobs from the run's own events.
        const runs = (cfg.runMode === 'task' && typeof TeamJobs !== 'undefined')
            ? TeamJobs.all().filter(t => t && t.routineId === note.id
                && (t.status === 'done' || t.status === 'failed')).slice(0, 20)
            : [];
        const runRows = runs.map(t => {
            const when = t.updatedAt
                ? new Date(t.updatedAt).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
                : '';
            const ok = t.status === 'done';
            return `
                <details class="routines-run${ok ? '' : ' is-error'}">
                    <summary class="routines-run-row">
                        <span class="routines-run-mark" aria-label="${ok ? 'Done' : 'Failed'}">${ok ? '&#10003;' : '&#10007;'}</span>
                        <span class="routines-post-when">${when}</span>
                        <span class="routines-post-preview">${esc(t.note || (ok ? 'Done.' : 'Did not finish.'))}</span>
                    </summary>
                    <pre class="routines-run-report">${linkify(esc(t.report || t.activity || 'No log was recorded for this run.'))}</pre>
                </details>`;
        }).join('');

        // What the routine draws on, as one quiet value line.
        const uses = [cfg.web ? 'Web search' : '', cfg.useContext ? 'My context' : '']
            .filter(Boolean).join(' &middot; ');
        const scheduleValue = cfg.offline
            ? esc(NotePrompts.triggerLabel(cfg))
            : (cfg.target === 'browser' ? 'runs as web search' : 'runs in Assistant');
        // C10: what this routine is allowed to DO, stated rather than implied.
        // "Can it change my data" is the question the merge made worth asking
        // on every routine, because the answer is no longer given by which
        // page you found it on.
        const modeValue = cfg.runMode === 'task'
            ? 'Takes actions &mdash; can change things, and pauses for permission'
            : 'Writes an answer &mdash; cannot change anything';
        const status = this._status(note.id);
        const lastError = status.lastError || '';
        // R4 (D4/T6): "nothing matched" and "this has been broken since the
        // day you armed it" looked identical, which is the only reason the D0
        // outage survived from C8.5 through C10. A checked stamp that is
        // absent says the engine has never evaluated this routine at all —
        // a different problem from one that evaluates and never matches.
        const checkedLabel = status.lastCheckedAt
            ? this._ago(status.lastCheckedAt)
            : 'not yet — the engine has not evaluated this routine';
        const matchedLabel = status.lastMatchedAt
            ? this._ago(status.lastMatchedAt)
            : (status.lastCheckedAt ? 'never matched anything yet' : 'never');
        // Only worth showing when it is NOT this Mac: naming the local
        // machine on every routine is noise on a single-Mac install.
        const elsewhere = cfg.homeMachineId
            && typeof RoutineEngine !== 'undefined' && RoutineEngine._machineId
            && cfg.homeMachineId !== RoutineEngine._machineId;
        // The Stop row (alpha.65) read `running` without ever defining it, so
        // every routine detail threw a ReferenceError before painting — the
        // list stayed on screen and "Edit routine" / record links seemed to
        // land on the wrong page (2026-09-09).
        const running = this._runningNow(note.id);
        const prop = (label, value) => `
            <div class="routines-prop">
                <span class="routines-prop-label">${label}</span>
                <span class="routines-prop-value">${value}</span>
            </div>`;

        // What it is ABOUT (RoutineAbout) — the records it reviews or
        // watches, as links. Built HERE, after `prop`: a const read before
        // its declaration throws, and a detail that throws paints nothing
        // at all (the alpha.65 lesson, 2026-09-09).
        //
        // A reference whose record the app cannot speak for right now is
        // NOT treated as gone (A2's tri-state) — it is named and simply not
        // struck, because a record whose app has not loaded is not a
        // deleted record.
        const aboutRefs = (typeof RoutineAbout !== 'undefined') ? RoutineAbout.resolve(cfg.about) : [];
        const aboutRow = aboutRefs.length ? prop('About', aboutRefs.map((r, i) =>
            `<button type="button" class="routines-about-link${r.exists === false ? ' is-gone' : ''}"
                     data-about="${i}"${r.exists === false ? ' disabled title="This record no longer exists"' : ''}
                ><span class="routines-about-type">${esc(r.typeLabel)}</span>${esc(r.label
                    || (r.exists === false ? 'deleted' : 'not loaded'))}${r.label && r.exists === false ? ' (deleted)' : ''}</button>`).join(' ')) : '';

        // Colour as data (2026-09-09): the routine's own hue and kind mark,
        // the same ones its editions carry on the home feed.
        const kind = cfg.runMode === 'task' ? 'task' : 'report';
        const hue = (typeof PromptFeed !== 'undefined' && PromptFeed.routineHue) ? PromptFeed.routineHue(note.id) : '#9CA3AF';
        const kindIcon = (typeof PromptFeed !== 'undefined' && PromptFeed.kindIcon) ? PromptFeed.kindIcon(kind, 20) : '';
        container.dataset.rtKind = kind;
        container.style.setProperty('--rt-hue', hue);
        // One sheet (2026-10-01, by request: "simplify … like the task and
        // project detail pages"): a head band with what kind of routine this
        // is and its actions, then the title, a condensed fact list and the
        // prompt as plain prose. No prompt pills or Decisions section here;
        // the floating "Ask about this routine" is the door to the assistant.
        const evented = cfg.offline && (cfg.trigger || {}).type && cfg.trigger.type !== 'time';
        container.innerHTML = `
            <div class="routines-sheet">
            <div class="routines-sheet-head">
                <div class="routines-detail-eyebrow">
                    <span class="routines-kind-chip">${cfg.runMode === 'task' ? 'Takes actions' : 'Writes an answer'}</span>
                    ${running ? '<span class="routines-mode-chip is-live">running</span>' : ''}
                    ${lastError ? '<span class="routines-err-chip">needs attention</span>' : ''}
                </div>
                <div class="routines-detail-actions">
                    <button class="primary-btn routines-act routines-act-run" data-run="${note.id}" type="button" title="Run this routine now">&#9654; Run now</button>
                    ${evented ? `<button class="secondary-btn routines-act" data-test="${note.id}" type="button" title="See what this trigger would fire on right now — nothing runs, nothing is recorded">Test trigger</button>` : ''}
                    <button class="secondary-btn routines-act" data-edit="${note.id}" type="button">Edit</button>
                    <button class="quiet-link-btn routines-act routines-act-delete" data-del="${note.id}" type="button">Delete</button>
                </div>
            </div>
            <div class="routines-sheet-body">
            <div class="routines-detail-head">
                <span class="routines-detail-tile" aria-hidden="true">${kindIcon}</span>
                <h3 class="routines-detail-title">${esc(note.title || 'Untitled routine')}</h3>
            </div>
            <div class="routines-props">
                ${prop('Runs when', scheduleValue)}
                ${aboutRow}
                ${uses ? prop('Uses', uses) : ''}
                ${running ? prop('Running now', `for ${esc(running)} <button class="secondary-btn routines-act routines-stop" data-stop="${esc(note.id)}" type="button" title="Stop this run">Stop</button>`) : ''}
                ${cfg.offline ? prop('Last run', esc(this._lastRunLabel(note))) : ''}
                ${stats.shown ? prop('Read', `You opened <strong>${stats.opened}</strong> of the last ${stats.shown}.`) : ''}
                ${quietStreak >= this.QUIET_STREAK_HINT
                    ? prop('Nothing to report', `The last ${quietStreak} runs had nothing to say, so nothing was posted. If that seems wrong, check the prompt &mdash; a routine that can never find anything says this every time.`)
                    : ''}
                ${cfg.offline && !status.lastCheckedAt ? prop('Last checked', esc(checkedLabel)) : ''}
                ${evented ? prop('Last matched', esc(matchedLabel)) : ''}
                ${status.queued ? prop('Queued', `${status.queued} run${status.queued > 1 ? 's' : ''} waiting for the task slot`) : ''}
                ${elsewhere ? prop('Runs on', 'Another Mac &mdash; it is armed there, not here') : ''}
                ${lastError ? prop('Last problem', `<span class="routines-err-text">${esc(lastError)}</span>`) : ''}
            </div>
            ${offerPrune ? `
            <div class="routines-prune">
                <p class="routines-prune-text">This has run ${stats.shown} times lately and you opened ${stats.opened === 0 ? 'none of them' : `${stats.opened} of them`}. Want it less often, or not at all?</p>
                <div class="routines-prune-actions">
                    ${cfg.interval !== 'weekly' && (cfg.trigger || {}).type === 'time'
                        ? `<button class="secondary-btn" type="button" data-prune="weekly">Make it weekly</button>` : ''}
                    <button class="secondary-btn routines-act-delete" type="button" data-prune="delete">Delete it</button>
                    <button class="secondary-btn" type="button" data-prune="keep">Keep it</button>
                </div>
            </div>` : ''}
            <div class="routines-trigtest" hidden></div>
            <div class="routines-prompt-section">
                <div class="detail-section-header">Prompt</div>
                <div class="routines-prompt-text">${esc(body) || '<span class="routines-empty">No prompt text yet — edit to add one.</span>'}</div>
            </div>
            </div>
            </div>
            ${runRows ? `
                <div class="routines-outputs">
                    <div class="detail-section-header">Run history</div>
                    ${runRows}
                </div>` : ''}
            ${postRows ? `
                <div class="routines-outputs">
                    <div class="detail-section-header">Run history</div>
                    ${postRows}
                </div>` : ''}
            ${!runRows && !postRows && cfg.offline ? `<p class="routines-empty">${cfg.runMode === 'task'
                ? 'No runs yet — each run&rsquo;s log will appear here.'
                : 'No runs yet — results will appear here and on your Home feed.'}</p>` : ''}
        `;

        container.querySelector('[data-run]')?.addEventListener('click', (e) => this._runNow(note.id, e.currentTarget));
        container.querySelector('[data-stop]')?.addEventListener('click', (e) => {
            e.currentTarget.disabled = true;
            const ok = typeof PromptFeed !== 'undefined' && PromptFeed.stopCurrent && PromptFeed.stopCurrent();
            UIUtils.showToast(ok ? 'Stopping…' : 'Nothing to stop — the run already ended', 'info');
            setTimeout(() => this.render(), 400);
        });
        container.querySelector('[data-test]')?.addEventListener('click', (e) => this._testTrigger(note, e.currentTarget));
        // A change is a conversation (2026-10-06): the routine's chat, where
        // update_routine's diff dialog is the confirmation.
        container.querySelector('[data-edit]')?.addEventListener('click', () => {
            if (this._embedHost) {
                this._embedHost = null;
                document.dispatchEvent(new CustomEvent('anjadhe:routine-embed-closed'));
                if (typeof PromptFeed !== 'undefined') PromptFeed.closePost();
            }
            this.askChange(note.id);
        });
        container.querySelector('[data-del]')?.addEventListener('click', () => this._delete(note.id));
        container.querySelectorAll('[data-about]').forEach(btn =>
            btn.addEventListener('click', () => {
                const ref = aboutRefs[Number(btn.dataset.about)];
                if (ref && typeof RoutineAbout !== 'undefined') RoutineAbout.open(ref);
            }));
        container.querySelector('[data-prune="keep"]')?.addEventListener('click', () => {
            this._dismissPrune(note.id);
            UIUtils.showToast('Kept — I won\'t ask about this one again', 'info');
            this.render();
        });
        container.querySelector('[data-prune="delete"]')?.addEventListener('click', () => this._delete(note.id));
        container.querySelector('[data-prune="weekly"]')?.addEventListener('click', () => {
            // The one write this card makes itself: it is the user's click
            // on a named change, which is consent (the old StarterPrompts.seed
            // rule), and the alternative — routing a one-word schedule
            // change through a chat turn — is slower than the form it
            // replaces.
            const next = { ...cfg, interval: 'weekly', trigger: { type: 'time', interval: 'weekly' } };
            NotePrompts.update(note.id, { config: next });
            this._dismissPrune(note.id);
            if (typeof RoutineEngine !== 'undefined') RoutineEngine.onRoutinesChanged();
            UIUtils.showToast('Now runs weekly', 'success');
            this.render();
        });
        container.querySelectorAll('.routines-detail-ask [data-ask]').forEach(b =>
            b.addEventListener('click', () => AgentUI.askWithPrompt(b.dataset.ask, { newChat: true })));
        container.querySelectorAll('[data-open-post]').forEach(b =>
            b.addEventListener('click', () => {
                if (typeof PromptFeed !== 'undefined' && PromptFeed.openPost) PromptFeed.openPost(b.dataset.openPost);
            }));
    },

    async _runNow(id, btn) {
        const note = this._note(id);
        if (!note) return;
        const cfg = NotePrompts.config(note);
        if (cfg.offline) {
            if (typeof PromptFeed === 'undefined' || !PromptFeed.runNow) return;
            if (btn) btn.disabled = true;
            await PromptFeed.runNow(id);
            this.render();
        } else {
            NotePrompts.runDefault(note);
        }
    },

    /**
     * R4 — "Test trigger". Reports what the matcher WOULD fire on, right
     * now, and stamps nothing: no run, no marker moved, no error recorded.
     * The cheapest thing in docs/ROUTINE_TRIGGERS.md's plan and the one that
     * would have caught D0 in under a minute.
     */
    async _testTrigger(note, btn) {
        const box = document.querySelector('#prompts-main .routines-trigtest');
        if (!box) return;
        const esc = UIUtils.escapeHtml;
        if (btn) btn.disabled = true;
        box.hidden = false;
        box.innerHTML = '<span class="routines-empty">Checking…</span>';
        let r;
        try { r = await RoutineEngine.testTrigger(note); }
        catch (e) { r = { error: e?.message || 'the check could not run' }; }
        if (btn) btn.disabled = false;

        const lines = [];
        if (r.error) {
            lines.push(`<span class="routines-err-text">Cannot check: ${esc(r.error)}</span>`);
        } else if (r.fired) {
            lines.push(`<strong>Would fire now.</strong> ${esc(r.suffix || 'The schedule slot is due.')}`);
            if (r.matches && r.matches.length > 1) {
                lines.push(`${r.matches.length} things match right now: ${esc(r.matches.slice(0, 5).join('; '))}${r.matches.length > 5 ? '…' : ''}`);
            }
        } else {
            lines.push('<strong>Would not fire now.</strong> Nothing matches since its last run.');
            if (r.scanned != null) {
                // `scanned` is the candidate window, not the whole mailbox:
                // mail since this routine was armed (R1's floor), or every
                // file in the watched folder.
                lines.push(r.type === 'email'
                    ? `${r.scanned} message${r.scanned === 1 ? '' : 's'} since this routine was armed ${r.scanned === 1 ? 'was' : 'were'} there to check.`
                    : `${r.scanned} file${r.scanned === 1 ? '' : 's'} in the watched folder ${r.scanned === 1 ? 'was' : 'were'} there to check.`);
            }
        }
        if (r.otherMachine) lines.push('This routine is armed on another Mac, so this one will not run it.');
        lines.push('<span class="routines-empty">Nothing was run and nothing was recorded.</span>');
        box.innerHTML = lines.map(l => `<p class="routines-trigtest-line">${l}</p>`).join('');
    },

    async _delete(id) {
        const note = this._note(id);
        const noun = note && NotePrompts.config(note).offline ? 'routine' : 'prompt';
        const ok = await UIUtils.confirm(
            `Delete ${noun}`,
            `Delete &ldquo;${UIUtils.escapeHtml(note?.title || `this ${noun}`)}&rdquo;? This removes the ${noun} and stops its scheduled runs. Past feed posts stay.`,
            '🗑️',
            { confirmText: 'Delete' }
        );
        if (!ok) return;
        NotePrompts.remove(id);
        if (typeof PromptFeed !== 'undefined' && PromptFeed.render) PromptFeed.render();
        if (this._openId === id) this._openId = null;
        this.render();
    }
};

AppManager.register('prompts', PromptsApp);

// One builder for the CURRENT ROUTINE block, used by the page provider (the
// routine open in the detail view) and the 'prompts' record resolver (a
// conversation attached to a routine, continued away from this page) — one
// builder so "this routine" cannot drift. Routines had no provider at all
// before the Decisions feature (2026-08-06), which meant no CURRENT ROUTINE
// block and no per-record conversation reattach; the recordKey
// ('prompts:<noteId>') is also what routes a routine's saved decisions into
// the ambient context (DecisionStore.fromRecordKey).
PromptsApp.routineContextBlock = function (noteId, opts = {}) {
    if (!noteId) return null;
    const note = PromptsApp._note(noteId);
    if (!note) return null;
    const cfg = NotePrompts.config(note);
    const body = NotePrompts.bodyText(note) || '';
    const lead = opts.attached
        ? 'This conversation is attached to this routine (the user may not have it open right now)'
        : 'The user is viewing this routine';
    return {
        recordKey: 'prompts:' + note.id,
        recordLabel: note.title || 'Untitled routine',
        title: 'CURRENT ROUTINE',
        body: `${lead} (id: ${note.id}):\n` +
            `Title: ${note.title || 'Untitled routine'}\n` +
            `Trigger: ${NotePrompts.triggerLabel(cfg)}\n` +
            `Mode: ${cfg.runMode === 'task' ? 'task (may act)' : 'digest (read-only post to the feed)'}\n` +
            `Prompt: ${body.slice(0, 400)}${body.length > 400 ? '…' : ''}\n` +
            `Use update_routine / delete_routine with this id for changes the user asks for.`
    };
};

if (typeof AgentContext !== 'undefined') {
    AgentContext.register('prompts', () => {
        if (PromptsApp._view !== 'detail' || !PromptsApp._openId) return null;
        return PromptsApp.routineContextBlock(PromptsApp._openId);
    });

    // Record resolver — rebuilds the CURRENT ROUTINE block from a
    // conversation's 'prompts:<id>' attachment when the chat is continued
    // away from the Routines page.
    AgentContext.registerRecord('prompts', (id) => PromptsApp.routineContextBlock(id, { attached: true }));
}

if (typeof module !== 'undefined' && module.exports) module.exports = PromptsApp;
